name: Testes Automátizados

on: 
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Instalar as Dependências do Site
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executar o Arquivo  
        run: |
          python -m pytest test_site/
