name: Testes Automatizados

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install pytest
          pip install requests  

      - name: Rodar Testes
        run: |
          python -m pytest tests/
